name: draftmode_notifier
description: your description
publish_to: "none"
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: "3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  generate: true
  plugin:
    platforms:
      ios:
        pluginClass: DraftmodeNotifierPlugin
